KEY_OVERRIDE_ENABLE		= no
COMBO_ENABLE 					= no
TAP_DANCE_ENABLE 			= no
KEYCOUNTER_ENABLE			= no
CAPS_WORD_ENABLE 			= no

# disable stuff to save space
GRAVE_ESC_ENABLE 			= no
MUSIC_ENABLE 					= no
MAGIC_ENABLE 					= no
SPACE_CADET_ENABLE 		= no
MOUSEKEY_ENABLE 			= no